// ── INTERVIEW QUESTIONS (25+ per field) ─────────────────────
const INTERVIEW_QUESTIONS = {
  'software-engineer': {
    label:'Software Engineer', icon:'💻', difficulty:'medium',
    questions:[
      {q:'Explain the difference between a process and a thread.',hint:'Talk about memory space, execution context, and when to use each.'},
      {q:'What is Big O notation? Give examples of O(1), O(n), O(n log n), O(n²).',hint:'Use array access, linear search, merge sort, and bubble sort as examples.'},
      {q:'What is the difference between REST and GraphQL? When would you choose one over the other?',hint:'Discuss over-fetching, under-fetching, flexible queries, caching.'},
      {q:'Explain SOLID principles with examples.',hint:'Single Responsibility, Open-Closed, Liskov Substitution, Interface Segregation, Dependency Inversion.'},
      {q:'What is a microservices architecture? What are its trade-offs vs monolith?',hint:'Think about deployment complexity, scaling benefits, inter-service communication.'},
      {q:'How does a database index work? When would you use one?',hint:'B-tree structure, read vs write trade-off, which columns to index.'},
      {q:'Explain the event loop in JavaScript / Node.js.',hint:'Call stack, callback queue, microtask queue, Web APIs.'},
      {q:'What is a distributed cache? How would you prevent cache stampede?',hint:'Redis/Memcached, mutex lock, probabilistic early expiry.'},
      {q:'How would you design a URL shortener like bit.ly?',hint:'Hashing, redirect logic, analytics, rate limiting, storage.'},
      {q:'What is a deadlock? How do you prevent it?',hint:'Four conditions for deadlock, ordering resources, timeouts.'},
      {q:'Explain the CAP theorem with a real-world example.',hint:'Consistency, Availability, Partition tolerance — pick 2. Cassandra vs MySQL.'},
      {q:'What is CI/CD? How have you used it in your projects?',hint:'Continuous Integration, Deployment pipelines, tools like Jenkins, GitHub Actions.'},
      {q:'What is a WebSocket? How does it differ from HTTP polling?',hint:'Persistent connection, real-time use cases, vs long polling.'},
      {q:'How does garbage collection work in your preferred language?',hint:'Reference counting, mark-and-sweep, generational GC.'},
      {q:'What is horizontal vs vertical scaling?',hint:'Adding more servers vs upgrading existing ones. Stateless apps scale horizontally.'},
      {q:'Explain the difference between SQL JOIN types.',hint:'INNER, LEFT, RIGHT, FULL OUTER, CROSS — with examples.'},
      {q:'What is a design pattern? Name 3 you have used and why.',hint:'Factory, Singleton, Observer, Strategy, Decorator — describe real usage.'},
      {q:'How would you handle a memory leak in a production Node.js app?',hint:'Heap profiling, event listener cleanup, stream backpressure.'},
      {q:'What is Docker? How does it differ from a Virtual Machine?',hint:'Container vs VM, namespaces, cgroups, lightweight overhead.'},
      {q:'Explain optimistic vs pessimistic locking in databases.',hint:'Conflict probability, READ/WRITE locking, versioning with ETags.'},
      {q:'What are webhooks? How would you make them reliable?',hint:'HTTP callbacks, retry logic, idempotency keys, signing with HMAC.'},
      {q:'Tell me about a bug you found and fixed that was hard to diagnose.',hint:'Talk about debugging methodology, tools used, and the fix.'},
      {q:'How do you approach writing unit tests? What is code coverage?',hint:'AAA pattern, mocking dependencies, 80% coverage heuristic.'},
      {q:'What is the difference between authentication and authorization?',hint:'JWT, OAuth2, RBAC — who you are vs what you can do.'},
      {q:'Walk me through how you would refactor a large, messy codebase.',hint:'Strangler fig pattern, tests first, incremental refactoring.'},
    ]
  },
  'data-science': {
    label:'Data Science / ML', icon:'📊', difficulty:'hard',
    questions:[
      {q:'What is the bias-variance trade-off in machine learning?',hint:'Underfitting vs overfitting. Regularization, model complexity.'},
      {q:'Explain the difference between supervised, unsupervised, and reinforcement learning.',hint:'Labeled vs unlabeled data, reward-based learning — with examples.'},
      {q:'How would you handle missing values in a dataset?',hint:'Mean/median imputation, KNN imputation, flagging with indicator variable.'},
      {q:'What is cross-validation? Why is it important?',hint:'k-fold CV, avoiding data leakage, reliable model evaluation.'},
      {q:'Explain precision, recall, F1-score and when to prioritize each.',hint:'Precision = correct of predicted. Recall = captured of actual. F1 = harmonic mean.'},
      {q:'What is gradient descent? How does learning rate affect it?',hint:'Local vs global minima, too large/small LR, Adam optimizer.'},
      {q:'Explain how a Random Forest works and why it reduces overfitting.',hint:'Ensemble of decision trees, bagging, feature subsampling.'},
      {q:'What is overfitting? How do you prevent it?',hint:'Regularization (L1/L2), dropout, early stopping, more data.'},
      {q:'How does Principal Component Analysis (PCA) work?',hint:'Dimensionality reduction, eigenvalues, variance explained.'},
      {q:'What is A/B testing? How do you determine sample size?',hint:'Hypothesis testing, statistical power, p-value, effect size.'},
      {q:'Explain the difference between bagging and boosting.',hint:'Parallel vs sequential ensemble. Random Forest vs XGBoost.'},
      {q:'What is a confusion matrix? What does each cell represent?',hint:'TP, TN, FP, FN — and how to calculate accuracy, precision, recall from it.'},
      {q:'What is the difference between L1 and L2 regularization?',hint:'L1 = Lasso (sparse weights). L2 = Ridge (shrinks all weights).'},
      {q:'How would you detect and handle outliers in a dataset?',hint:'Z-score, IQR method, winsorization, isolation forest.'},
      {q:'What is data leakage? Give a real-world example.',hint:'Future data leaking into training. E.g., using post-event features in a predictive model.'},
      {q:'Explain the attention mechanism in Transformer models.',hint:'Query, Key, Value. Scaled dot-product. Self-attention vs cross-attention.'},
      {q:'What is a recommendation system? What are collaborative vs content-based filtering?',hint:'User-item matrix factorization vs item feature similarity.'},
      {q:'How do you evaluate a clustering algorithm?',hint:'Silhouette score, elbow method for k-means, DBSCAN density.'},
      {q:'What is feature engineering? Give 3 techniques you use.',hint:'Binning, log transform, interaction features, target encoding.'},
      {q:'Explain what happens when your model performs well in training but poorly in production.',hint:'Distribution shift, train-test leakage, feedback loops.'},
      {q:'What is SHAP? How do you explain model predictions to a non-technical stakeholder?',hint:'SHapley values, feature importance, local vs global explainability.'},
      {q:'How would you build a real-time ML inference system?',hint:'Model serving (FastAPI/TF Serving), latency vs throughput, caching.'},
      {q:'What is the difference between a parametric and non-parametric model?',hint:'Fixed parameters (Linear Regression) vs flexible (KNN, decision tree).'},
      {q:'How do you monitor a model in production for drift?',hint:'Feature drift, concept drift, PSI, SHAP drift, retraining triggers.'},
      {q:'Describe a machine learning project you built end-to-end.',hint:'Problem framing, data collection, EDA, modelling, deployment, monitoring.'},
    ]
  },
  'product-manager': {
    label:'Product Manager', icon:'📋', difficulty:'medium',
    questions:[
      {q:'Tell me about yourself and why you want to be a Product Manager.',hint:'Story: background → why PM → key skills you bring.'},
      {q:'How would you prioritize a backlog with 50 feature requests?',hint:'RICE, ICE, MoSCoW, Impact vs Effort matrix.'},
      {q:'Design a new feature for Zomato to increase repeat orders.',hint:'User pain points → hypothesis → success metrics → MVP.'},
      {q:'How do you measure the success of a product feature?',hint:'North Star Metric, leading vs lagging indicators, guardrail metrics.'},
      {q:'How would you improve WhatsApp for Indian users?',hint:'User research, pain points (rural users, voice messages, groups), proposed features + metrics.'},
      {q:'A metric you own has dropped 20% week-over-week. Walk me through your investigation.',hint:'Isolate: external vs internal. Segment: by platform, location, user type. Diagnose: funnel analysis.'},
      {q:'How do you balance technical debt vs new features?',hint:'Allocate 20% of sprint to tech debt. Involve engineering in prioritization. Quantify the risk of deferral.'},
      {q:'Describe the product development lifecycle.',hint:'Discovery → Definition → Design → Development → Testing → Launch → Iteration.'},
      {q:'How do you conduct user research?',hint:'User interviews, surveys, usability tests, data analysis, Jobs-to-be-Done framework.'},
      {q:'What is the difference between a KPI and a North Star Metric?',hint:'NSM = single metric capturing core product value. KPIs = operational metrics tracking execution.'},
      {q:'How would you launch a product in a new market (e.g., Tier 3 India)?',hint:'Market sizing, localization, pricing, GTM strategy, partnerships.'},
      {q:'How do you work with engineering teams to ship on time?',hint:'Spec clarity, unblocking daily, managing scope, agile ceremonies.'},
      {q:'What is a Product Requirements Document (PRD)? What goes in it?',hint:'Problem statement, goals, user stories, acceptance criteria, open questions.'},
      {q:'How do you handle conflicting stakeholder priorities?',hint:'Align to business goals, use data, involve leadership only when needed.'},
      {q:'What would you do if engineering says a feature will take 6 months but sales promised it in 2?',hint:'Scope reduction, phased delivery, stakeholder management, setting expectations early.'},
      {q:'How do you think about pricing for a SaaS product?',hint:'Value-based vs cost-plus, freemium, tiered plans, price sensitivity testing.'},
      {q:'Walk me through an example of a product decision you made using data.',hint:'Hypothesis → metric → experiment → result → decision.'},
      {q:'What is the difference between output and outcome metrics?',hint:'Output = features shipped. Outcome = user behavior changed. Measure outcomes.'},
      {q:'How would you build a roadmap for a 0-to-1 product?',hint:'Discovery first. Validate assumptions cheaply. Build MVP → iterate based on data.'},
      {q:'What would you do in the first 90 days as a PM at a new company?',hint:'Listen, learn, align. Know users, business, and team. Identify quick wins.'},
      {q:'How do you handle a feature that users love but is costing the company money?',hint:'Quantify value vs cost. Look for optimization. Consider pricing or paywalling.'},
      {q:'Describe a product failure and what you learned from it.',hint:'Own it. Focus on learnings. Show how it changed your process.'},
      {q:'How do you decide between building in-house vs buying vs partnering?',hint:'Build: core competency. Buy: faster time-to-market. Partner: non-core needs.'},
      {q:'What is product-market fit? How do you know you have it?',hint:'Sean Ellis test (40% very disappointed), retention curves flattening, NPS, organic growth.'},
      {q:'How would you design a product for a first-generation smartphone user in rural India?',hint:'Vernacular language, offline-first, low data, feature phone muscle memory, voice UI.'},
    ]
  },
  'ux-designer': {
    label:'UX / UI Designer', icon:'🎨', difficulty:'easy',
    questions:[
      {q:'Walk me through your design process from problem to final design.',hint:'Discover → Define → Ideate → Prototype → Test → Iterate.'},
      {q:'What is the difference between UX and UI design?',hint:'UX = experience and flow. UI = visual design and interaction. Both must work together.'},
      {q:'How do you conduct usability testing?',hint:'Recruit 5 users, task-based testing, think-aloud protocol, analyze patterns.'},
      {q:'Explain the concept of "affordance" in UX design.',hint:'Design communicates how it should be used. Door handles, buttons, links.'},
      {q:'How would you redesign the UPI payment flow for first-time users?',hint:'Fear of failure, confirmation steps, error states, simple language.'},
      {q:'What is information architecture? How do you approach it for a complex app?',hint:'Sitemap, card sorting, tree testing, navigation patterns.'},
      {q:'What are heuristics in UX? Name 5 Nielsen heuristics.',hint:'Visibility, match with real world, user control, consistency, error prevention.'},
      {q:'How do you design for accessibility (a11y)?',hint:'WCAG 2.1, color contrast, screen reader compatibility, keyboard navigation, alt text.'},
      {q:'What is a design system? Why is it important?',hint:'Reusable components + guidelines. Consistency, faster development, brand coherence.'},
      {q:'Walk me through a time you used user data to improve a design.',hint:'Metrics that showed pain point → hypothesis → design change → outcome.'},
      {q:'How do you approach designing for Tier 2/3 Indian users?',hint:'Low literacy, slow internet, Hindi/vernacular, feature phone muscle memory, trust signals.'},
      {q:'What is the difference between a wireframe, mockup, and prototype?',hint:'Wireframe = structure. Mockup = visual. Prototype = interactive flow.'},
      {q:'How do you handle stakeholder feedback that conflicts with user research?',hint:'Data + empathy. Show user testing evidence. Propose compromise.'},
      {q:'What is progressive disclosure and when do you use it?',hint:'Show only what is needed at each step. Complex forms, settings, onboarding.'},
      {q:'How would you improve the Swiggy onboarding flow?',hint:'Current pain points, personalization, social proof, reduce time to first value.'},
      {q:'What tools do you use in your design workflow and why?',hint:'Figma for design, Maze/Maze for testing, FigJam for workshops, Zeplin for handoff.'},
      {q:'How do you measure the success of a UX design change?',hint:'Task completion rate, time-on-task, error rate, SUS score, business metrics.'},
      {q:'What is dark UX/dark patterns? Give 3 examples.',hint:'Hidden unsubscribe, roach motels, confirmshaming, misdirection, fake urgency.'},
      {q:'How would you present your design work to engineers?',hint:'Context first, show variants, explain rationale, edge cases, design tokens/handoff files.'},
      {q:'Tell me about the most challenging design problem you have worked on.',hint:'Problem complexity + your process + trade-offs + outcome.'},
      {q:'How do you prioritize design work when everything is urgent?',hint:'Align with product roadmap, impact on user + business, effort estimate.'},
      {q:'What is emotional design? How do you design for delight?',hint:'Don Norman: visceral, behavioral, reflective. Micro-animations, surprise moments.'},
      {q:'How do you approach responsive design for mobile-first India?',hint:'Mobile-first CSS, touch targets (48px), network-aware loading, small screen typography.'},
      {q:'What are the main patterns for mobile navigation?',hint:'Tab bar, hamburger, bottom sheet, gesture-based (swipe). Trade-offs of each.'},
      {q:'Describe your portfolio and the most impactful project in it.',hint:'Problem → your role → process → outcome → what you learned.'},
    ]
  },
  'marketing': {
    label:'Marketing & Growth', icon:'📢', difficulty:'easy',
    questions:[
      {q:'What is the difference between growth marketing and brand marketing?',hint:'Growth = measurable acquisition/retention. Brand = awareness and perception.'},
      {q:'Walk me through a full-funnel marketing strategy for a new product launch in India.',hint:'Awareness → Interest → Consideration → Intent → Purchase → Loyalty.'},
      {q:'How would you increase Meesho\'s monthly active sellers by 20% in one quarter?',hint:'Identify drop-off points, referral program, seller education content, local partnerships.'},
      {q:'What is SEO? What are the key ranking factors in 2025?',hint:'Core Web Vitals, E-E-A-T, backlinks, mobile-first, structured data, helpful content.'},
      {q:'How do you measure the ROI of a marketing campaign?',hint:'CAC, LTV, ROAS, CPC, conversion rate, attribution models.'},
      {q:'What is content marketing? How would you build a content strategy from scratch?',hint:'Audience → keyword research → pillar content → distribution → repurposing.'},
      {q:'How would you grow a brand\'s Instagram from 10K to 100K followers in 6 months?',hint:'Consistency, Reels (highest reach), collabs, UGC, hashtag strategy, posting time.'},
      {q:'What is a customer persona? How do you create one?',hint:'Demographics, goals, pain points, channel preferences — built from interviews + data.'},
      {q:'How do you approach email marketing to avoid spam filters?',hint:'Sender reputation, list hygiene, authentication (SPF/DKIM), relevance, unsubscribe link.'},
      {q:'What is attribution in digital marketing? Explain the difference between last-click and data-driven.',hint:'Who gets credit for a conversion. Last-click oversimplifies. Data-driven uses ML.'},
      {q:'How would you run a performance marketing campaign on Meta for a fintech app?',hint:'Target audience, creative strategy, A/B testing, optimization events, budget allocation.'},
      {q:'What is influencer marketing? How do you measure its effectiveness?',hint:'Macro vs micro vs nano influencers. Reach, engagement rate, tracked links, promo codes.'},
      {q:'How do you write a compelling value proposition?',hint:'Who you serve + problem you solve + why you are different. One clear sentence.'},
      {q:'What is product-led growth (PLG)? Give an Indian startup example.',hint:'Users adopt product through usage, not salespeople. Notion, Figma, Canva India model.'},
      {q:'How would you use WhatsApp for growth marketing in India?',hint:'Broadcast lists, WhatsApp Business API, chatbots, catalog, personalized messaging.'},
      {q:'What is a Net Promoter Score (NPS)? How do you act on NPS data?',hint:'0-10 scale. Detractors (0-6), Passives (7-8), Promoters (9-10). Close the loop.'},
      {q:'What is retargeting and how does the Facebook Pixel work?',hint:'Serving ads to people who visited your site. Pixel fires events, builds custom audiences.'},
      {q:'How do you approach marketing to vernacular/regional language audiences in India?',hint:'Translated content isn\'t enough. Cultural context, local influencers, regional platforms.'},
      {q:'What is a funnel? Describe the marketing funnel for an ed-tech company.',hint:'Awareness (blog/YT) → Lead (free course) → Nurture (email) → Convert (enroll) → Retain.'},
      {q:'How do you write a great call-to-action (CTA)?',hint:'Action verb + specific benefit + urgency. "Start learning free for 7 days" vs "Click here".'},
      {q:'What is cohort analysis? How do you use it for retention marketing?',hint:'Group users by signup week, track retention over time, spot drop-offs, tailor campaigns.'},
      {q:'Tell me about a marketing campaign you ran that did not perform well. What did you learn?',hint:'Honest reflection on hypothesis, what was measured, why it failed, what you changed.'},
      {q:'How would you build a community around a B2C product?',hint:'Owned community (Discord/WhatsApp) → content → events → user stories → advocacy.'},
      {q:'What is programmatic advertising?',hint:'Automated buying of ad inventory using DSPs, SSPs, DMPs, RTB. Benefits vs brand safety.'},
      {q:'How do you stay updated with the latest marketing trends?',hint:'Newsletters, podcasts, following thought leaders, experimenting on your own profiles.'},
    ]
  },
  'finance': {
    label:'Finance & Accounting', icon:'💰', difficulty:'medium',
    questions:[
      {q:'Walk me through the three financial statements and how they connect.',hint:'Income Statement → Net Income → Balance Sheet. Cash Flow Statement reconciles changes.'},
      {q:'What is working capital? How do you calculate it?',hint:'Current Assets – Current Liabilities. Positive = healthy short-term liquidity.'},
      {q:'What is EBITDA and why is it used for valuation?',hint:'Earnings Before Interest, Tax, Depreciation, Amortisation. Proxy for operating cash flow.'},
      {q:'How would you value a startup with no revenue?',hint:'DCF on projected cash flows, comparable transactions, VC method (exit × ownership).'},
      {q:'What is the difference between equity and debt financing?',hint:'Equity = ownership dilution. Debt = interest obligation. Trade-offs in WACC, control, risk.'},
      {q:'Explain the concept of Net Present Value (NPV) and IRR.',hint:'NPV = PV of cash flows – initial investment. IRR = discount rate where NPV = 0.'},
      {q:'What is a discounted cash flow (DCF) model?',hint:'Project free cash flows → discount at WACC → terminal value → enterprise value.'},
      {q:'What is the difference between gross profit and net profit?',hint:'Gross = Revenue – COGS. Net = after all operating expenses, interest, and tax.'},
      {q:'What is P/E ratio? When is it useful and when is it misleading?',hint:'Price per share / EPS. Misleading for companies with no earnings, cyclical businesses.'},
      {q:'How do you assess a company\'s liquidity?',hint:'Current ratio, quick ratio, cash ratio, operating cash flow to current liabilities.'},
      {q:'What is a leveraged buyout (LBO)?',hint:'Acquisition using significant debt secured against target assets. PE firms use this.'},
      {q:'What is the difference between GAAP and IFRS?',hint:'US vs International accounting standards. Revenue recognition, lease accounting differences.'},
      {q:'How do you read a cash flow statement?',hint:'Operating (core business), Investing (capex/M&A), Financing (debt/equity). Free Cash Flow = Operating – Capex.'},
      {q:'What is amortization vs depreciation?',hint:'Depreciation = tangible assets. Amortization = intangible assets. Both are non-cash.'},
      {q:'How would you analyze if a company has too much debt?',hint:'Debt/Equity, Debt/EBITDA (3-4x threshold), Interest Coverage Ratio (>2x).'},
      {q:'What is goodwill on a balance sheet? When is it impaired?',hint:'Premium paid above fair value in acquisitions. Impaired when performance falls short.'},
      {q:'What is a rights issue?',hint:'Existing shareholders offered new shares at discount to raise capital proportionally.'},
      {q:'How do interest rate changes affect bond prices?',hint:'Inverse relationship. Higher rates → lower bond prices. Duration measures sensitivity.'},
      {q:'What is SEBI? What are its main functions?',hint:'Securities regulator in India. Protects investors, regulates IPOs, exchanges, mutual funds.'},
      {q:'How would you structure a financial model for a new product launch?',hint:'Revenue drivers → COGS → operating expenses → cash flow → sensitivity analysis.'},
      {q:'What is the difference between a mutual fund and an ETF?',hint:'MF = actively managed, NAV once daily. ETF = passively managed, trades on exchange.'},
      {q:'What is ESOP? How is it typically structured?',hint:'Employee Stock Option Plan. Vesting schedule, exercise price, cliff period.'},
      {q:'How do you perform a sensitivity analysis?',hint:'Identify key assumptions → vary them ±10-20% → see impact on output (NPV/EPS).'},
      {q:'What is the role of a CFO in a startup vs a large corporation?',hint:'Startup: fundraising, runway management, FP&A. Corp: capital allocation, investor relations, risk.'},
      {q:'Tell me about a financial analysis you performed and the insight you delivered.',hint:'Context + methodology + data + insight + business decision made from it.'},
    ]
  },
};
